;;; js2hl-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from js2hl.el

(autoload 'js2hl-show-thing-at-point "js2hl" "\
Highlight all occurrences of the thing at point.
Use this when the point is on a variable, and it will
highlight all usages of it in its defining scope.  You can also
use it on strings, numbers or literal regexps (highlights
occurrences in the whole buffer), or on keywords `this' and
`super' (highlights occurrences in the current function)." t)
(autoload 'js2hl-show-exits "js2hl" "\
Show exit points from the function surrounding point.
That is, `return' and `throw' statements." t)
(autoload 'js2hl-rename-thing-at-point "js2hl" "\
Replace the highlighted things with NEW-NAME.
If N > 0, only occurrences in current N lines are renamed.

(fn &optional N)" t)
(autoload 'js2hl-add-namespace-to-thing-at-point "js2hl" "\
Prepend the highlighted things with new namespace.
If N > 0, only occurrences in current N lines are changed.
Namespace separator from `js2hl-namespace-separator' is automatically inserted.
Given the thing \"var1\" and namespace \"sp1\", the new thing is \"sp1.var1\".

(fn &optional N)" t)
(autoload 'js2hl-forget-it "js2hl" "\
Exit the highlight minor mode." t)
(autoload 'js2hl-move-next "js2hl" "\
Move cursor to the next highlighted node." t)
(autoload 'js2hl-move-prev "js2hl" "\
Move cursor to the previous highlighted node." t)
(autoload 'js2hl-mode "js2hl" "\
Internal mode used by `js2hl'.

This is a minor mode.  If called interactively, toggle the `JS2HL mode'
mode.  If the prefix argument is positive, enable the mode, and if it is
zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `js2hl-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "js2hl" '("js2hl-"))

;;; End of scraped data

(provide 'js2hl-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; js2hl-autoloads.el ends here
